def COLOR_MAP = [
    'SUCESS': 'good',
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK21"
    }
    
    environment {
        cluster = "vproapp-prod"
        service = "vprofileapptask-service-prod"
    }

    stages {
        stage('Deploy to prod ecs') {
            steps {
                withAWS(credentials: 'awscreds', region: 'ap-southeast-2') {
                    sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }
        }
    }
}    
    